root: true
extends:
  - "@pentible/eslint-config"
  - "@pentible/eslint-config-web"
  - "@pentible/eslint-config-react"
  - "@pentible/eslint-config-prettier"
rules:
  # TODO: revert once we type bugout proper
  "@typescript-eslint/no-unsafe-assignment": "off"
  "@typescript-eslint/no-unsafe-call": "off"
  "@typescript-eslint/no-unsafe-member-access": "off"
  "@typescript-eslint/no-unsafe-return": "off"
  # TODO: shouldn't be required here
  "import/no-unassigned-import":
    [
      "error",
      {
        allow:
          [
            "**/*.css",
            "ghspa",
            "@fontsource/**",
            "@testing-library/jest-dom",
            "@testing-library/jest-dom/**",
          ],
      },
    ]

overrides:
  - files:
      - "*.tsx"
      - "src/components/**"
    rules:
      "@typescript-eslint/naming-convention":
        - "error"
        # default
        - selector: "default"
          format: ["strictCamelCase"]
          leadingUnderscore: "forbid"
          trailingUnderscore: "forbid"
        # unused variable
        - selector: "variableLike"
          modifiers: ["unused"]
          format: ["strictCamelCase"]
          leadingUnderscore: "allow"
        # quoted properties on object literals (to ease interfacing with external code)
        - selector: "objectLiteralProperty"
          modifiers: ["requiresQuotes"]
          format: null
        # types & enum members
        - selector: ["typeLike", "enumMember"]
          format: ["StrictPascalCase"]
        # react components / styled components
        - selector: ["function", "variable"]
          # modifiers: ["exported"]
          format: ["strictCamelCase", "StrictPascalCase"]
  # TODO: revert once we type bugout proper
  - files:
      - "bugout.d.ts"
    rules:
      "@typescript-eslint/no-explicit-any": "off"
      "@typescript-eslint/naming-convention": "off"
  # TODO: shouldn't be required here...
  - files:
      - "*.d.ts"
    rules:
      "import/no-unassigned-import": "off"
