version: '3.6'
services:
  proxy:
    image: pentible/basic-nginx
    environment:
      SERVER_CONFIG: |
        location / {
          proxy_pass http://client:3000;

          # websocket support for react devtools
          proxy_set_header Upgrade $$http_upgrade;
          proxy_set_header Connection "Upgrade";
        }

        location /api {
          proxy_pass http://server:8100;
        }
    ports:
      - '80:80'
  server:
    build:
      context: .
      target: development
    command: ["npm", "run", "debug:server"]
    environment:
      SERVER_BASE_PATH: /api
    ports:
      - '9229:9229' # debugging port
    volumes:
      - './server/src:/var/build/server/src:delegated'
  client:
    build:
      context: .
      target: development
    command: ["npm", "run", "debug:client"]
    volumes:
      - './client/src:/var/build/client/src:delegated'
      - './client/public:/var/build/client/public:delegated'
