version: '3.6'
services:
  web:
    build:
      context: web
      target: development
      # args:
      #   PUBLIC_URL: /secret
    ports:
      - '80:80'
    volumes:
      - './web/src:/var/app/src:delegated'
      - './web/public:/var/app/public:delegated'
