version: "3.6"
services:
  web:
    build:
      context: .
      target: development
      # args:
      #   PUBLIC_URL: /secret
    ports:
      - "80:80"
    volumes:
      - "./src:/var/app/src:delegated"
      - "./public:/var/app/public:delegated"
