name: build
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build secret-share
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push to registry
      uses: docker/build-push-action@v2
      with:
        context: .
        tags: ghcr.io/${{ github.repository }}:latest
        push: true
        cache-from: type=gha
        cache-to: type=gha,mode=max

# TODO: consider auto generating tags for docker images (ie. by getting the latest release & incrementing it: https://github.com/pozetroninc/github-action-get-latest-release)
