name: deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy secret-share
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Install dependencies
        run: npm install
      - name: Build
        # TODO: re-enable eslint once bugout fixed
        run: DISABLE_ESLINT_PLUGIN=true npm run build
        env:
          PUBLIC_URL: /secret-share
      - name: Setup 404 as index
        # TODO: if we eject maytbe we can make this automatic with webpack
        run:
          sed -E 's@<title>Secret Share</title>@<title>404</title>@g'
          <build/index.html >build/404.html
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
